import assert from 'node:assert/strict'
import { editorCode } from './test-config.mjs'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync } from 'node:child_process'
import { chromium, devices } from 'playwright-core'

// Creates fixtures and boards. Run only against an isolated XP_CANVAS_STATE_PATH server.
const baseURL = process.env.BASE_URL ?? 'http://127.0.0.1:5175'
const run = `corrections-${Date.now()}`
const fixtures = await mkdtemp(join(tmpdir(), 'xp-canvas-corrections-fixtures-'))
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--disable-gpu'] })
const context = await browser.newContext({ ...devices['iPad Pro 11 landscape'], baseURL })
const viewer = await browser.newContext({ baseURL })
const page = await context.newPage()
page.setDefaultTimeout(20_000)
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
const cdp = await context.newCDPSession(page)
const api = async (path, method = 'GET', data) => {
	const response = await context.request.fetch(`/api/${path}`, { method, ...(data === undefined ? {} : { data }) })
	assert.ok(response.ok(), `${method} ${path}: ${response.status()} ${await response.text()}`)
	return response.json()
}
const ready = () => page.waitForFunction(() => Boolean(window.__xpCanvasEditor))
const contact = (id, x, y, radius = 10) => ({ id, x, y, radiusX: radius, radiusY: radius })
const touch = (type, points) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: points })
const frame = () => page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))))
const camera = () => page.evaluate(() => ({ ...window.__xpCanvasEditor.getCamera() }))

try {
	assert.equal((await viewer.request.get('/api/resource-folders')).status(), 403)
	assert.equal((await viewer.request.post('/api/resource-folders', { data: { name: 'denied' } })).status(), 403)
	await api('editor-session', 'POST', { code: editorCode })
	const board = await api('boards', 'POST', { name: run })
	execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=s=320x180:d=4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-movflags', '+faststart', join(fixtures, 'clip.mp4')])
	const videoBytes = await readFile(join(fixtures, 'clip.mp4'))
	const oldId = `legacy-${Date.now()}`
	const oldUpload = await context.request.post(`/api/uploads/${oldId}`, { data: videoBytes, headers: { 'content-type': 'video/mp4', 'x-file-name': `${run}-legacy.mp4`, 'x-save-resource': 'true' } })
	assert.equal(oldUpload.status(), 201)
	const old = (await oldUpload.json()).resource
	assert.equal(old.previewSrc, undefined)
	assert.equal((await viewer.request.patch(`/api/resources/${old.id}`, { data: { folderId: null } })).status(), 403)
	assert.equal((await context.request.patch(`/api/resources/${old.id}`, { data: { folderId: 'missing' } })).status(), 400)
	assert.equal((await viewer.request.put(`/api/resources/${old.id}/preview`, { data: { previewId: old.id } })).status(), 403)
	assert.equal((await context.request.put(`/api/resources/${old.id}/preview`, { data: { previewId: old.id } })).status(), 400)

	await page.goto(`/board/${board.id}`); await ready()
	assert.match(await page.getByTestId('ipad-toolbar.resources').locator('svg path').getAttribute('d'), /^M3 7/)
	await page.getByTestId('ipad-toolbar.resources').tap()
	const oldCard = page.getByRole('button', { name: `Insertar ${old.name}`, exact: true })
	await oldCard.locator('img').waitFor()
	await oldCard.locator('img').evaluate((image) => image.decode())
	const repaired = (await api('resources')).resources.find((item) => item.id === old.id)
	assert.match(repaired.previewSrc, /^\/api\/uploads\//)
	assert.deepEqual(await (await viewer.request.get(old.src)).body(), videoBytes)
	console.log('Video preview: existing upload repaired with a persistent frame; original bytes unchanged.')

	await page.getByRole('button', { name: 'Nueva carpeta de recursos', exact: true }).tap()
	await page.getByLabel('Nombre', { exact: true }).fill(run)
	await page.getByRole('button', { name: 'Guardar', exact: true }).tap()
	await page.getByRole('button', { name: `Abrir carpeta ${run}`, exact: true }).tap()
	await page.getByRole('button', { name: 'Nueva carpeta de recursos', exact: true }).tap()
	await page.getByLabel('Nombre', { exact: true }).fill(`${run}-clips`)
	await page.getByRole('button', { name: 'Guardar', exact: true }).tap()
	await page.getByRole('button', { name: `Abrir carpeta ${run}-clips`, exact: true }).tap()
	const folderData = await api('resource-folders')
	const parent = folderData.folders.find((item) => item.name === run), child = folderData.folders.find((item) => item.name === `${run}-clips`)
	assert.equal(child.parentId, parent.id)
	assert.equal((await context.request.patch(`/api/resource-folders/${parent.id}`, { data: { parentId: child.id } })).status(), 400)
	assert.equal((await api('library')).folders.some((item) => item.id === parent.id), false, 'Resource folders are separate from board folders')
	await page.getByLabel('Archivos para recursos').setInputFiles({ name: `${run}-new.mp4`, mimeType: 'video/mp4', buffer: videoBytes })
	const newCard = page.getByRole('button', { name: `Insertar ${run}-new.mp4`, exact: true })
	await newCard.locator('img').waitFor()
	const uploaded = (await api('resources')).resources.find((item) => item.name === `${run}-new.mp4`)
	assert.equal(uploaded.folderId, child.id)
	assert.ok(uploaded.previewSrc)
	await page.getByRole('button', { name: 'Carpeta anterior', exact: true }).tap()
	await page.getByRole('button', { name: 'Carpeta anterior', exact: true }).tap()
	await page.getByRole('button', { name: `Opciones de ${old.name}`, exact: true }).tap()
	await page.getByRole('menuitem', { name: 'Mover a carpeta', exact: true }).click()
	await page.getByLabel('Carpeta de destino').selectOption(child.id)
	await page.getByRole('button', { name: 'Mover', exact: true }).tap()
	assert.equal(await oldCard.count(), 0)
	await page.getByRole('button', { name: `Abrir carpeta ${run}`, exact: true }).tap()
	await page.getByRole('button', { name: `Abrir carpeta ${run}-clips`, exact: true }).tap()
	await oldCard.waitFor()
	assert.equal((await api('resources')).resources.find((item) => item.id === old.id).folderId, child.id)
	await newCard.tap()
	const videoId = await page.evaluate(() => window.__xpCanvasEditor.getOnlySelectedShapeId())
	await page.getByRole('button', { name: 'Cerrar recursos', exact: true }).tap()
	const video = page.locator(`[data-shape-id="${videoId}"] video`)
	await page.locator('.tlui-video__toolbar [data-testid="delete-selection"]').waitFor({ state: 'visible' })
	assert.equal(await page.locator('.tlui-video__toolbar [data-testid="tool.video-alt-text"]').count(), 1, 'Native video actions remain alongside delete')
	const poster = page.locator(`[data-shape-id="${videoId}"] .canvas-video__poster`)
	const play = page.getByTestId(`video-play-${videoId}`)
	assert.equal(await poster.getAttribute('src'), uploaded.previewSrc, 'Canvas video shows its resource thumbnail before play')
	assert.equal(await video.count(), 0, 'Unplayed videos use a lightweight image instead of an active media element')
	await page.evaluate((id) => {
		const e = window.__xpCanvasEditor, asset = e.getAsset(e.getShape(id).props.assetId)
		e.updateAssets([{ id: asset.id, type: 'video', meta: {} }])
	}, videoId)
	const syncObserver = await viewer.newPage()
	await syncObserver.goto(`/board/${board.id}`)
	await syncObserver.waitForFunction(id => {
		const editor = window.__xpCanvasEditor, shape = editor?.getShape(id)
		return shape && !editor.getAsset(shape.props.assetId)?.meta.previewSrc
	}, videoId)
	await page.reload(); await ready()
	await poster.waitFor()
	assert.equal(await poster.getAttribute('src'), uploaded.previewSrc, 'Already-inserted assets recover existing thumbnails after reload')
	await play.tap()
	await page.waitForFunction((id) => document.querySelector(`[data-shape-id="${id}"] video`)?.currentTime > .1, videoId)
	assert.equal(await video.evaluate((element) => element.controls), false)
	assert.equal(await play.count(), 0, 'Custom button disappears while playback is active')
	await video.tap()
	assert.equal(await video.evaluate((element) => element.controls), true, 'Native controls appear only after a tap')
	assert.equal(await play.count(), 0, 'Never duplicate native and custom transport controls')
	assert.deepEqual(await video.evaluate(element => ({ muted: element.muted, loop: element.loop })), { muted: false, loop: false })
	await video.evaluate(element => element.pause())
	assert.equal(await play.count(), 0, 'Paused native controls remain without a duplicate Play button')
	assert.equal(await video.count(), 1, 'Pausing retains the decoded frame and player')
	assert.equal(await poster.count(), 0, 'Pausing does not jump back to the thumbnail')
	console.log('Resources: nested folders, scoped uploads, file moves, thumbnails and tap-only video controls passed.')

	await page.reload(); await ready()
	await page.getByTestId('ipad-toolbar.resources').tap()
	await page.getByRole('button', { name: `Abrir carpeta ${run}`, exact: true }).tap()
	await page.getByRole('button', { name: `Abrir carpeta ${run}-clips`, exact: true }).tap()
	await oldCard.locator('img').waitFor(); await newCard.locator('img').waitFor()
	assert.equal(await newCard.locator('.resource-card__kind').getAttribute('aria-label'), 'Video')
	assert.equal(await newCard.locator('.resource-card__kind svg').count(), 1)
	assert.equal(await newCard.locator('.resource-card__kind').textContent(), '')
	await page.getByRole('button', { name: 'Cerrar recursos', exact: true }).tap()
	const gestureBoard = await api('boards', 'POST', { name: `${run}-gestures` })
	await page.goto(`/board/${gestureBoard.id}`); await ready()
	await page.evaluate(() => { window.__xpCanvasEditor.setCurrentTool('draw').updateInstanceState({ isPenMode: true }) })
	for (const delay of [0, 250, 1200]) {
		await page.evaluate(() => { window.__xpCanvasEditor.setCamera({ x: 0, y: 0, z: 1 }) })
		await touch('touchStart', [contact(1, 600, 600)])
		for (let i = 1; i <= 6; i++) await touch('touchMove', [contact(1, 600 + i * 10, 600)])
		await frame()
		const panned = await camera()
		assert.ok(Math.abs(panned.x - 60) < 2)
		if (delay) await page.waitForTimeout(delay)
		await touch('touchStart', [contact(1, 660, 600), contact(2, 800, 600, 30)])
		await frame()
		assert.ok(Math.abs((await camera()).x - panned.x) < 1, 'Adding the second finger never jumps the camera')
		for (let i = 1; i <= 6; i++) await touch('touchMove', [contact(1, 660 - i * 8, 600), contact(2, 800 + i * 8, 600, 30)])
		await frame()
		const pinched = await camera()
		assert.ok(pinched.z > 1.5, `A 60px thumb must join the gesture after ${delay}ms`)
		// CDP lists the contacts that end, not the contacts remaining on the glass.
		await touch('touchEnd', [contact(1, 612, 600)])
		await touch('touchMove', [contact(2, 878, 600, 30)])
		await frame()
		const remaining = await camera()
		assert.equal(remaining.z, pinched.z)
		assert.ok(Math.abs(remaining.x - pinched.x - 30 / pinched.z) < 2)
		await touch('touchEnd', [])
	}
	assert.equal(await page.evaluate(() => window.__xpCanvasEditor.getCurrentPageShapes().length), 0, 'No gesture creates an accidental drawing')
	await page.evaluate((resource) => {
		const editor = window.__xpCanvasEditor
		editor.setCamera({ x: 0, y: 0, z: 1 })
		editor.createAssets([{ id: 'asset:pinch-video', type: 'video', typeName: 'asset', meta: {}, props: { src: resource.src, name: resource.name, mimeType: resource.mimeType, w: 320, h: 180, isAnimated: true } }])
		editor.createShape({ id: 'shape:pinch-video', type: 'video', x: 740, y: 400, props: { assetId: 'asset:pinch-video', w: 320, h: 180 } })
	}, uploaded)
	const videoPlay = page.getByTestId('video-play-shape:pinch-video')
	const initialButton = await videoPlay.boundingBox()
	const y = initialButton.y + initialButton.height / 2
	const startX = initialButton.x - 360
	await touch('touchStart', [contact(1, startX, y)])
	await touch('touchMove', [contact(1, startX + 30, y)]); await frame()
	const movingButton = await videoPlay.boundingBox()
	const secondX = movingButton.x + movingButton.width / 2
	await touch('touchStart', [contact(1, startX + 30, y), contact(2, secondX, y, 30)])
	for (let i = 1; i <= 6; i++) await touch('touchMove', [contact(1, startX + 30 - i * 15, y), contact(2, secondX + i * 15, y, 30)])
	await touch('touchEnd', []); await frame()
	assert.ok((await camera()).z > 1.3, 'The second finger can join over a video control')
	assert.equal(await page.locator('[data-shape-id="shape:pinch-video"] video').evaluate((element) => element.paused), true, 'A joining finger never activates Play')
	console.log('Touch: pan then add a thumb at 0/250/1200ms, pinch, lift one finger and continue panning passed.')
	assert.deepEqual(errors, [])
	console.log('Corrections smoke passed.')
} catch (error) {
	console.error('Page errors:', errors)
	console.error('Canvas diagnostic:', await page.evaluate(() => ({ shapes: window.__xpCanvasEditor?.getCurrentPageShapes().map(s => ({ id: s.id, type: s.type })), videos: window.__xpCanvasEditor?.getAssets().filter(a => a.type === 'video').map(a => ({ id: a.id, meta: a.meta })) })).catch(() => null))
	throw error
} finally {
	await browser.close()
	await rm(fixtures, { recursive: true })
}
