import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { chromium, devices } from 'playwright-core'
import { verifyProfileControls, selectProfileSkin, verifyInlinePassEditor, verifyProfileRefinements } from './portal-controls-checks.mjs'

// Writes synthetic accounts and boards. Only run on the isolated portal QA server.
const baseURL = process.env.BASE_URL ?? 'http://127.0.0.1:5177'
if (!['localhost', '127.0.0.1'].includes(new URL(baseURL).hostname)) throw new Error('Portal smoke only runs on localhost with isolated state.')
const teacherPassword = process.env.PORTAL_QA_PASSWORD ?? 'qa-teacher-password-only-local'
const stamp = randomUUID().replaceAll('-', '').slice(0, 9).toUpperCase()
const anaUsername = `A${stamp}`, luisUsername = `B${stamp}`, groupName = `Grupo QA ${stamp}`
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] })
const errors = []
try {
	const teacher = await browser.newContext({ baseURL }), student = await browser.newContext({ ...devices['iPad Pro 11 landscape'], baseURL }), anonymous = await browser.newContext({ baseURL })
	for (const context of [teacher, student, anonymous]) context.on('page', (page) => page.on('pageerror', (error) => errors.push(error.message)))
	await student.addInitScript(() => {
		window.__portalSockets = []; window.__portalClosed = []; window.__portalPushAcks = 0
		const Original = window.WebSocket
		window.WebSocket = new Proxy(Original, { construct(Target, args) {
			const socket = new Target(...args)
			if (String(args[0]).includes('/api/connect/')) {
				window.__portalSockets.push(socket)
				socket.addEventListener('close', (event) => window.__portalClosed.push(event.code))
				socket.addEventListener('message', (event) => { if (String(event.data).includes('push_result')) window.__portalPushAcks++ })
				const send = socket.send.bind(socket)
				socket.send = (raw) => {
					let data
					try { data = JSON.parse(raw) } catch { return send(raw) }
					if (data.type === 'push' && data.presence && window.__forgeNextPortalPush) {
						const shape = window.__forgeNextPortalPush
						data.diff = { [shape.id]: ['put', shape] }
						if (data.presence[0] === 'put') Object.assign(data.presence[1], { userId: 'user:teacher', userName: 'Profesor falso' })
						else Object.assign(data.presence[1], { userId: ['put', 'user:teacher'], userName: ['put', 'Profesor falso'] })
						window.__forgeNextPortalPush = null
						return send(JSON.stringify(data))
					}
					return send(raw)
				}
			}
			return socket
		} })
	})
	assert.deepEqual(await (await anonymous.request.get('/api/portal/session')).json(), { mode: 'portal', user: null })
	for (const path of ['/api/library', '/api/boards/principal', '/api/boards/principal/thumbnail', '/api/resources', '/api/uploads/unknown-upload-123']) assert.equal((await anonymous.request.get(path)).status(), 401, path)
	assert.equal((await anonymous.request.post('/api/portal/login', { data: { username: 'leo', password: teacherPassword }, headers: { origin: 'https://hostile.test' } })).status(), 403)
	const manager = await teacher.newPage()
	await manager.goto('/')
	await manager.getByRole('heading', { name: 'Entra a tus clases', exact: true }).waitFor()
	assert.equal((await manager.locator('.portal-entry-card').innerText()).replace(/\s+/g, ' ').trim(), 'Entra a tus clases Matrícula Contraseña Mostrar contraseña Entrar')
	await manager.getByLabel('Mostrar contraseña', { exact: true }).check()
	assert.equal(await manager.getByLabel('Contraseña', { exact: true }).getAttribute('type'), 'text')
	await manager.getByLabel('Mostrar contraseña', { exact: true }).uncheck()
	assert.equal(await manager.getByLabel('Contraseña', { exact: true }).getAttribute('type'), 'password')
	await manager.getByLabel('Matrícula', { exact: true }).fill('leo')
	await manager.getByLabel('Contraseña', { exact: true }).fill(teacherPassword)
	await manager.getByRole('button', { name: 'Entrar', exact: true }).click()
	await manager.getByTestId('board-manager').waitFor()
	await manager.getByRole('button', { name: 'Cuenta de Leo', exact: true }).click()
	await manager.getByRole('menuitem', { name: 'Papelera', exact: true }).click()
	await manager.getByRole('heading', { name: 'Papelera', exact: true }).waitFor()
	assert.equal(await manager.getByRole('button', { name: 'Papelera', exact: true }).count(), 0)
	await manager.getByRole('button', { name: 'Cuenta de Leo', exact: true }).click()
	await manager.getByRole('menuitem', { name: 'Mi perfil', exact: true }).click()
	await manager.getByRole('heading', { name: 'Mi perfil', exact: true }).waitFor()
	assert.equal(await manager.getByLabel('Contraseña actual', { exact: true }).count(), 0)
	await manager.getByRole('button', { name: 'Cuenta de Leo', exact: true }).click()
	await manager.getByRole('menuitem', { name: 'Alumnos', exact: true }).click()
	await manager.getByTestId('students-admin').waitFor()
	const teacherViewport = manager.viewportSize()
	await manager.setViewportSize({ width: 320, height: 850 })
	await manager.getByRole('button', { name: 'Mostrar carpetas', exact: true }).waitFor()
	assert(await manager.locator('.board-main').evaluate((el) => el.scrollWidth <= el.clientWidth + 1), 'teacher account layout at 320px')
	await manager.setViewportSize(teacherViewport)
	await manager.getByRole('button', { name: 'Cuenta de Leo', exact: true }).waitFor()
	await manager.getByRole('button', { name: 'Nuevo grupo', exact: true }).click()
	let dialog = manager.getByRole('dialog')
	await dialog.getByLabel('Nombre', { exact: true }).fill(groupName)
	await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
	await dialog.waitFor({ state: 'hidden' })
	await manager.getByRole('button', { name: 'Añadir alumnos', exact: true }).click()
	dialog = manager.getByRole('dialog')
	await dialog.getByLabel('Lista de alumnos').fill(`${anaUsername}; Ana Prueba\n${luisUsername}; Luis Prueba`)
	await dialog.getByRole('combobox').selectOption({ label: groupName })
	await dialog.getByRole('button', { name: 'Guardar', exact: true }).click()
	await dialog.waitFor({ state: 'hidden' })
	const roster = await (await teacher.request.get('/api/portal/roster')).json()
	const ana = roster.students.find((s) => s.username === anaUsername), luis = roster.students.find((s) => s.username === luisUsername), group = roster.groups.find((g) => g.name === groupName)
	assert(ana && luis && group)
	assert.equal((await teacher.request.patch(`/api/portal/students/${luis.id}`, { data: { groupId: null } })).status(), 200)
	assert.equal((await teacher.request.post('/api/portal/students', { data: { students: [{ username: anaUsername, name: 'Overwrite attempt' }] } })).status(), 409)
	const board = await (await teacher.request.post('/api/boards', { data: { name: `Clase ${stamp}` } })).json()
	const privateBoard = await (await teacher.request.post('/api/boards', { data: { name: `Privado ${stamp}` } })).json()
	const termFolder = await (await teacher.request.post('/api/folders', { data: { name: `Semestre ${stamp}` } })).json()
	const classFolder = await (await teacher.request.post('/api/folders', { data: { name: `Clase compartida ${stamp}`, parentId: termFolder.id } })).json()
	const privateFolder = await (await teacher.request.post('/api/folders', { data: { name: `Carpeta privada ${stamp}`, parentId: termFolder.id } })).json()
	assert.equal((await teacher.request.patch(`/api/boards/${board.id}`, { data: { folderId: classFolder.id } })).status(), 200)
	assert.equal((await teacher.request.patch(`/api/boards/${privateBoard.id}`, { data: { folderId: privateFolder.id } })).status(), 200)
	await manager.goto('/')
	await manager.getByRole('button', { name: `Opciones de ${board.name}`, exact: true }).click()
	await manager.getByRole('menuitem', { name: 'Compartir con alumnos', exact: true }).click()
	dialog = manager.getByRole('dialog')
	await dialog.getByLabel(groupName, { exact: true }).check()
	await dialog.getByRole('button', { name: 'Guardar accesos', exact: true }).click()
	await dialog.getByText('Accesos guardados.', { exact: true }).waitFor()
	await dialog.getByRole('button', { name: 'Cerrar', exact: true }).click()
	await manager.goto(`/board/${board.id}`)
	await manager.waitForFunction(() => !!window.__xpCanvasEditor)
	assert.equal(await manager.getByRole('button', { name: 'Seguir a Leo', exact: true }).count(), 0)
	assert.equal(await manager.getByRole('button', { name: 'Levantar la mano', exact: true }).count(), 0)
	await manager.getByText('Todavía no hay alumnos conectados.', { exact: true }).waitFor()
	assert.equal(await manager.locator('.tlui-share-zone').count(), 0)
	const initialViewport = manager.viewportSize()
	for (const width of [1440, 1024, 768]) {
		await manager.setViewportSize({ width, height: 900 })
		const rail = manager.getByTestId('ipad-toolbar')
		await rail.waitFor({ state: 'visible' })
		const bounds = await rail.boundingBox()
		assert(bounds.x < 20 && bounds.width < 80, 'teacher tools sit on the left with a mouse')
		await manager.getByTestId('tools.draw').click()
		assert.equal(await manager.evaluate(() => window.__xpCanvasEditor.getCurrentToolId()), 'draw')
		for (const selector of ['.header-resources', '.header-emojis', '.header-quick-shape', '.canvas-actions > .snap-hold']) assert.equal(await manager.locator(selector).isVisible(), false)
		const stage = await manager.locator('.canvas-stage').boundingBox()
		const sidebar = await manager.getByRole('complementary', { name: 'Alumnos conectados', exact: true }).boundingBox()
		assert(stage.x + stage.width <= sidebar.x + 1, 'students do not cover the desktop canvas')
		await manager.getByRole('button', { name: 'Colapsar alumnos conectados', exact: true }).click()
		assert((await manager.locator('.canvas-stage').boundingBox()).width > stage.width + 100)
		await manager.getByRole('button', { name: 'Mostrar alumnos conectados', exact: true }).click()
	}
	await manager.setViewportSize(initialViewport)

	const firstLogin = await anonymous.request.post('/api/portal/login', { data: { username: anaUsername.toLowerCase(), password: anaUsername.toLowerCase() } })
	assert.equal(firstLogin.status(), 200); assert.equal((await firstLogin.json()).user.mustChangePassword, true)
	for (const path of ['/api/library', `/api/boards/${board.id}`, '/api/resources']) assert.equal((await anonymous.request.get(path)).status(), 403)
	assert.equal((await anonymous.request.get(`/api/connect/${board.id}?sessionId=abcdefghijklmnop`, { headers: { upgrade: 'websocket' } })).status(), 403)
	const viewer = await student.newPage()
	await viewer.goto('/')
	await viewer.getByLabel('Matrícula', { exact: true }).fill(anaUsername)
	await viewer.getByLabel('Contraseña', { exact: true }).fill(anaUsername)
	await viewer.getByRole('button', { name: 'Entrar', exact: true }).click()
	await viewer.getByRole('heading', { name: 'Elige tu contraseña' }).waitFor()
	assert.equal((await viewer.locator('.portal-entry-card').innerText()).replace(/\s+/g, ' ').trim(), 'Elige tu contraseña Nueva contraseña Repite la contraseña Mostrar contraseña Guardar y continuar Cerrar sesión')
	assert.equal((await student.request.post('/api/portal/password', { data: { password: anaUsername } })).status(), 400)
	await viewer.getByLabel('Nueva contraseña', { exact: true }).fill('una frase de prueba segura')
	await viewer.getByLabel('Repite la contraseña', { exact: true }).fill('una frase de prueba segura')
	await viewer.getByRole('button', { name: 'Guardar y continuar' }).click()
	await viewer.getByRole('button', { name: 'Comenzar', exact: true }).click()
	assert.equal((await student.request.get('/api/library')).status(), 403, 'welcome must be complete before accessing class data')
	await viewer.getByRole('button', { name: 'Firma', exact: true }).click()
	const signature = viewer.getByLabel('Dibuja tu firma con el cursor o el dedo', { exact: true })
	await signature.press('Space')
	await signature.press('ArrowRight')
	await signature.press('ArrowUp')
	await signature.press('ArrowRight')
	await signature.press('Space')
	await viewer.getByRole('button', { name: 'Listo, guardar firma', exact: true }).click()
	await viewer.getByRole('button', { name: 'Continuar', exact: true }).click()
	await viewer.getByRole('button', { name: 'Continuar', exact: true }).click()
	await viewer.getByRole('button', { name: 'Rasgar el sobre hacia la izquierda', exact: true }).press('Enter')
	await viewer.getByRole('button', { name: 'Continuar', exact: true }).click()
	await viewer.getByRole('button', { name: 'Descargar imagen', exact: true }).waitFor()
	await viewer.getByRole('button', { name: 'Continuar', exact: true }).click()
	await viewer.getByRole('button', { name: 'Insertar pase y entrar a mis clases', exact: true }).press('Enter')
	await viewer.getByTestId('student-boards').waitFor()
	assert.equal((await anonymous.request.get('/api/library')).status(), 401, 'password change revokes other initial sessions')
	assert.equal((await anonymous.request.post('/api/portal/login', { data: { username: anaUsername, password: anaUsername } })).status(), 401)
	const studentLibrary = await (await student.request.get('/api/library')).json()
	assert.deepEqual(studentLibrary.boards.map((b) => b.id), [board.id])
	assert.equal(studentLibrary.boards[0].folderId, classFolder.id)
	assert.deepEqual(studentLibrary.folders.map((f) => f.id).sort(), [termFolder.id, classFolder.id].sort())
	await viewer.getByRole('button', { name: classFolder.name, exact: true }).waitFor()
	assert.equal(await viewer.getByRole('button', { name: privateFolder.name, exact: true }).count(), 0)
	assert.equal(await viewer.getByTestId('pass-card').count(), 0, 'no pass banner in class library')
	await viewer.getByRole('button', { name: termFolder.name, exact: true }).click()
	await viewer.getByRole('heading', { name: termFolder.name, exact: true }).waitFor()
	await viewer.getByRole('button', { name: classFolder.name, exact: true }).click()
	await viewer.getByRole('heading', { name: classFolder.name, exact: true }).waitFor()
	await viewer.goBack()
	await viewer.getByRole('heading', { name: termFolder.name, exact: true }).waitFor()
	await viewer.getByRole('button', { name: 'Todas', exact: true }).click()
	await viewer.getByRole('heading', { name: 'Mis clases', exact: true }).waitFor()
	assert.equal((await student.request.get(`/api/boards/${privateBoard.id}`)).status(), 404)
	assert.equal((await student.request.get('/api/portal/roster')).status(), 403)
	assert.equal((await student.request.post('/api/boards', { data: { name: 'No permission' } })).status(), 403)
	assert.equal((await student.request.post('/api/editor-session', { data: { code: 'anything' } })).status(), 403)
	assert.equal((await student.request.get('/api/resources')).status(), 404)
	assert.equal((await student.request.get(`/api/boards/${board.id}/export`)).status(), 404)
	assert.equal((await student.request.post('/api/boards/import', { data: {} })).status(), 403)
	await viewer.getByRole('button', { name: 'Cuenta de Ana Prueba', exact: true }).click()
	assert.deepEqual(await viewer.getByRole('menuitem').allTextContents(), ['Mi perfil', 'Cerrar sesión'])
	await viewer.getByRole('menuitem', { name: 'Mi perfil', exact: true }).click()
	await viewer.getByRole('heading', { name: 'Mi perfil', exact: true }).waitFor()
	assert.equal(await viewer.getByLabel('Contraseña actual', { exact: true }).count(), 0)
	const studentViewport = viewer.viewportSize()
	for (const width of [320, 390, 650, 651, 821, 900, 1024, 1440]) {
		await viewer.setViewportSize({ width, height: 850 })
		if (width <= 650) {
			const trigger = viewer.getByRole('button', { name: 'Mostrar carpetas', exact: true })
			await trigger.waitFor()
			await trigger.click()
			await viewer.getByRole('dialog', { name: 'Carpetas de canvases', exact: true }).waitFor()
			assert(await viewer.locator('.board-sidebar-mobile').evaluate((el) => el.contains(document.activeElement)), 'mobile navigation owns focus')
			await viewer.keyboard.press('Escape')
			await viewer.getByRole('dialog', { name: 'Carpetas de canvases', exact: true }).waitFor({ state: 'hidden' })
			await viewer.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Mostrar carpetas')
			assert(await trigger.evaluate((el) => el === document.activeElement), 'Escape returns focus to the menu trigger')
			if (width === 320) {
				await trigger.click()
				await viewer.getByRole('button', { name: 'Cuenta de Ana Prueba', exact: true }).click()
				await viewer.getByRole('menuitem', { name: 'Mi perfil', exact: true }).click()
				await viewer.getByRole('dialog', { name: 'Carpetas de canvases', exact: true }).waitFor({ state: 'hidden' })
				await viewer.getByRole('button', { name: 'Girar pase', exact: true }).click()
				assert.equal(await viewer.locator('.pass-carousel-card[data-selected="true"] .pass-card').getAttribute('data-back'), 'true')
				await viewer.getByRole('button', { name: 'Girar pase', exact: true }).click()
			}
		} else await viewer.getByRole('button', { name: 'Cuenta de Ana Prueba', exact: true }).waitFor()
		assert(await viewer.locator('.board-main').evaluate((el) => el.scrollWidth <= el.clientWidth + 1), `Profile overflow at ${width}px`)
		for (const name of ['Girar pase', 'Personalizar mi pase', 'Descargar imagen']) {
			const bounds = await viewer.getByRole('button', { name, exact: true }).boundingBox()
			assert(bounds.width >= 44 && bounds.height >= 44, `${name} touch target at ${width}px`)
		}
	}
	await viewer.setViewportSize(studentViewport)
	const pointerContext = await browser.newContext({ baseURL, viewport: { width: 1440, height: 900 }, storageState: await student.storageState() })
	const pointerPage = await pointerContext.newPage()
	pointerPage.on('pageerror', (error) => errors.push(error.message))
	await pointerPage.goto('/perfil')
	await verifyProfileControls(pointerPage)
	await verifyInlinePassEditor(pointerPage)
	await verifyProfileRefinements(pointerPage)
	await pointerContext.close()
	// The independent profile check saves and restores this synthetic pass.
	// Refresh the original tab's revision before making another edit.
	await viewer.reload()
	await viewer.getByRole('heading', { name: 'Mi perfil', exact: true }).waitFor()
	for (const name of ['Girar pase', 'Personalizar mi pase', 'Descargar imagen']) assert.equal((await viewer.getByRole('button', { name, exact: true }).innerText()).trim(), '')
	await viewer.getByRole('button', { name: 'Girar pase', exact: true }).click()
	assert.equal(await viewer.locator('.pass-carousel-card[data-selected="true"] .pass-card').getAttribute('data-back'), 'true')
	const backDownload = viewer.waitForEvent('download')
	await viewer.getByRole('button', { name: 'Descargar imagen', exact: true }).click()
	assert.equal((await backDownload).suggestedFilename(), 'pase-xp-ana-reverso.png')
	await viewer.getByRole('button', { name: 'Girar pase', exact: true }).click()
	assert.equal(await viewer.locator('.pass-carousel-card[data-selected="true"] .pass-card').getAttribute('data-back'), 'false')
	const downloaded = viewer.waitForEvent('download')
	await viewer.getByRole('button', { name: 'Descargar imagen', exact: true }).click()
	assert.equal((await downloaded).suggestedFilename(), 'pase-xp-ana.png')
	await viewer.getByRole('button', { name: 'Personalizar mi pase', exact: true }).click()
	await selectProfileSkin(viewer, 'halo')
	await viewer.getByRole('button', { name: 'Arrastrar Estrella', exact: true }).press('Enter')
	await viewer.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
	await viewer.locator('.portal-profile[data-editing="false"]').waitFor()
	const customized = await (await student.request.get('/api/portal/pass')).json()
	assert.equal(customized.draft.skin, 'halo')
	assert.equal(customized.draft.stickers.length, 1)
	assert(customized.completed)
	await viewer.reload()
	await viewer.getByRole('heading', { name: 'Mi perfil', exact: true }).waitFor()
	assert.equal(await viewer.locator('.profile-card-stage .pass-carousel-card[data-selected="true"] .pass-sticker').count(), 1)
	await viewer.getByRole('button', { name: 'Repetir la bienvenida', exact: true }).click()
	await viewer.getByRole('button', { name: 'Comenzar', exact: true }).waitFor()
	assert.equal((await student.request.get('/api/library')).status(), 200, 'replaying does not revoke completed access')
	await viewer.goto('/perfil')
	await viewer.getByRole('button', { name: 'Cambiar contraseña', exact: true }).click()
	await viewer.getByLabel('Contraseña actual', { exact: true }).fill('contraseña incorrecta')
	await viewer.getByLabel('Nueva contraseña', { exact: true }).fill('otra frase de prueba segura')
	await viewer.getByLabel('Repite la contraseña', { exact: true }).fill('otra frase de prueba segura')
	await viewer.getByRole('button', { name: 'Actualizar contraseña', exact: true }).click()
	await viewer.getByText('La contraseña actual no es correcta.', { exact: true }).waitFor()
	await viewer.getByLabel('Contraseña actual', { exact: true }).fill('una frase de prueba segura')
	await viewer.getByRole('button', { name: 'Actualizar contraseña', exact: true }).click()
	await viewer.getByText('Contraseña actualizada. Tus otras sesiones se cerraron.', { exact: true }).waitFor()
	await viewer.getByRole('button', { name: 'Volver', exact: true }).click()
	const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')
	const uploadId = randomUUID(), unplacedId = randomUUID()
	for (const id of [uploadId, unplacedId]) assert.equal((await teacher.request.post(`/api/uploads/${id}`, { data: png, headers: { 'content-type': 'image/png', 'x-file-name': 'qa.png' } })).status(), 201)
	assert.equal((await student.request.post(`/api/uploads/${randomUUID()}`, { data: png, headers: { 'content-type': 'image/png' } })).status(), 403)
	await manager.evaluate(({ uploadId }) => {
		const editor = window.__xpCanvasEditor
		editor.createAssets([{ id: 'asset:portal-image', typeName: 'asset', type: 'image', props: { name: 'QA', src: `/api/uploads/${uploadId}`, w: 100, h: 100, mimeType: 'image/png', isAnimated: false }, meta: {} }])
		editor.createShapes([{ id: 'shape:portal-image', type: 'image', x: 100, y: 100, props: { assetId: 'asset:portal-image', w: 100, h: 100 } }, { id: 'shape:portal-geo', type: 'geo', x: 300, y: 200 }])
	}, { uploadId })
	await viewer.getByRole('button', { name: `Abrir ${board.name}`, exact: true }).tap()
	await viewer.waitForFunction(() => !!window.__xpCanvasEditor?.getShape('shape:portal-geo'))
	assert.equal(await viewer.evaluate(() => window.__xpCanvasEditor.getInstanceState().isReadonly), true)
	assert.equal(await viewer.getByTestId('canvas-grid-toggle').count(), 0)
	assert.equal(await viewer.evaluate(() => window.__xpCanvasEditor.getCurrentToolId()), 'hand')
	assert.deepEqual(await viewer.locator('.tlui-main-toolbar [data-testid^="tools."]').evaluateAll((buttons) => buttons.map((button) => button.dataset.testid)), ['tools.hand'])
	for (const name of ['Compartir', 'Guardar copia', 'Salir', 'Salir de edición']) assert.equal(await viewer.getByRole('button', { name, exact: true }).count(), 0)
	await viewer.locator('.tl-background').click({ position: { x: 50, y: 100 } })
	for (const key of ['v', 'l', 'Escape']) {
		await viewer.keyboard.press(key)
		assert.equal(await viewer.evaluate(() => window.__xpCanvasEditor.getCurrentToolId()), 'hand', `viewer remains in hand after ${key}`)
	}
	const zoomBefore = await viewer.evaluate(() => window.__xpCanvasEditor.getZoomLevel())
	await viewer.mouse.move(600, 400)
	await viewer.mouse.wheel(0, -120)
	await viewer.waitForFunction((zoom) => window.__xpCanvasEditor.getZoomLevel() > zoom, zoomBefore)
	const cameraBefore = await viewer.evaluate(() => ({ ...window.__xpCanvasEditor.getCamera() }))
	await viewer.mouse.move(600, 400); await viewer.mouse.down(); await viewer.mouse.move(650, 450, { steps: 8 }); await viewer.mouse.up()
	await viewer.waitForFunction((camera) => Math.abs(window.__xpCanvasEditor.getCamera().x - camera.x) > 5, cameraBefore)
	assert.equal(await viewer.getByRole('button', { name: 'Editar', exact: true }).count(), 0)
	await viewer.mouse.move(400, 350)
	await manager.waitForFunction((id) => window.__xpCanvasEditor.getCollaborators().some((peer) => peer.userId === `user:${id}` && peer.userName === 'Ana Prueba'), ana.id)
	await viewer.getByRole('button', { name: 'Seguir a Leo', exact: true }).waitFor({ state: 'visible' })
	await viewer.locator('.tlui-people-menu__avatars-button').click()
	await viewer.locator('.tlui-people-menu__wrapper').waitFor({ state: 'visible' })
	assert.equal(await viewer.getByTestId('people-menu.change-name').count(), 0)
	assert.equal(await viewer.locator('.tlui-people-menu__user__input').count(), 0)
	await viewer.keyboard.press('Escape')

	const studentsPanel = manager.getByRole('complementary', { name: 'Alumnos conectados', exact: true })
	await studentsPanel.getByText('Ana Prueba', { exact: true }).waitFor()
	assert.equal(await studentsPanel.locator('li').count(), 1)
	const secondTab = await student.newPage()
	await secondTab.goto(`/board/${board.id}`)
	await secondTab.waitForFunction(() => !!window.__xpCanvasEditor)
	await secondTab.mouse.move(200, 200)
	await manager.waitForFunction((id) => window.__xpCanvasEditor.store.allRecords().filter((peer) => peer.typeName === 'instance_presence' && peer.userId === `user:${id}`).length === 2, ana.id)
	assert.equal(await studentsPanel.locator('li').count(), 1, 'one row per student across tabs')
	assert.equal(await manager.locator('.connected-students__toggle .connected-students__count').innerText(), '1')
	const handIndicator = studentsPanel.getByRole('img', { name: 'Mano levantada', exact: true })
	const documentBeforeHands = (await (await teacher.request.get(`/api/boards/${board.id}/export`)).json()).snapshot.documents
	await viewer.getByRole('button', { name: 'Levantar la mano', exact: true }).tap()
	await handIndicator.waitFor({ state: 'visible' })
	assert.equal(await viewer.getByRole('button', { name: 'Bajar la mano', exact: true }).getAttribute('aria-pressed'), 'true')
	await secondTab.mouse.move(250, 220)
	await manager.waitForFunction((id) => window.__xpCanvasEditor.getCollaborators().some((peer) => peer.userId === `user:${id}` && peer.meta.handRaised === false), ana.id)
	assert.equal(await handIndicator.count(), 1, 'another tab moving does not erase the raised hand')
	await viewer.getByRole('button', { name: 'Bajar la mano', exact: true }).tap()
	await handIndicator.waitFor({ state: 'hidden' })
	await secondTab.getByRole('button', { name: 'Levantar la mano', exact: true }).tap()
	await handIndicator.waitFor({ state: 'visible' })
	await secondTab.close()
	await handIndicator.waitFor({ state: 'hidden' })
	assert.equal(await studentsPanel.locator('li').count(), 1, 'the remaining tab keeps the student connected')
	await viewer.getByRole('button', { name: 'Levantar la mano', exact: true }).tap()
	await handIndicator.waitFor({ state: 'visible' })
	await viewer.reload()
	await viewer.waitForFunction(() => !!window.__xpCanvasEditor)
	await handIndicator.waitFor({ state: 'hidden' })
	assert.equal(await viewer.getByRole('button', { name: 'Levantar la mano', exact: true }).getAttribute('aria-pressed'), 'false')
	assert.equal(await viewer.evaluate(() => window.__xpCanvasEditor.getInstanceState().isReadonly), true)
	assert.equal(await viewer.evaluate(() => window.__xpCanvasEditor.getCurrentToolId()), 'hand')
	assert.deepEqual((await (await teacher.request.get(`/api/boards/${board.id}/export`)).json()).snapshot.documents, documentBeforeHands, 'raising hands does not modify the canvas document')
	await viewer.getByRole('button', { name: 'Seguir a Leo', exact: true }).click()
	await viewer.waitForFunction(() => window.__xpCanvasEditor.getInstanceState().followingUserId === 'user:teacher')
	await viewer.evaluate(() => { window.__xpCanvasEditor.stopFollowingUser() })

	const visibleAsset = await student.request.get(`/api/uploads/${uploadId}`)
	assert.equal(visibleAsset.status(), 200); assert.equal(visibleAsset.headers()['cache-control'], 'private, no-store'); assert.deepEqual(await visibleAsset.body(), png)
	assert.equal((await student.request.head(`/api/uploads/${uploadId}`)).status(), 200)
	assert.equal((await student.request.get(`/api/uploads/${uploadId}`, { headers: { range: 'bytes=0-7' } })).status(), 206)
	assert.equal((await student.request.get(`/api/uploads/${unplacedId}`)).status(), 404)
	assert.equal((await anonymous.request.get(`/api/uploads/${uploadId}`, { headers: { 'if-none-match': visibleAsset.headers().etag } })).status(), 401)
	const forgedShape = await manager.evaluate(() => ({ ...window.__xpCanvasEditor.getShape('shape:portal-geo'), id: 'shape:forged' }))
	const previousAcks = await viewer.evaluate((shape) => { window.__forgeNextPortalPush = shape; return window.__portalPushAcks }, forgedShape)
	await viewer.mouse.move(450, 370)
	await viewer.waitForFunction((count) => !window.__forgeNextPortalPush && window.__portalPushAcks > count, previousAcks)
	await manager.waitForFunction((id) => window.__xpCanvasEditor.getCollaborators().some((peer) => peer.userId === `user:${id}` && peer.userName === 'Ana Prueba'), ana.id)
	assert.equal(await manager.evaluate(() => Boolean(window.__xpCanvasEditor.getShape('shape:forged'))), false)
	await manager.evaluate(() => { window.__xpCanvasEditor.updateShape({ id: 'shape:portal-geo', type: 'geo', props: { color: 'blue' } }) })
	await viewer.waitForFunction(() => window.__xpCanvasEditor.getShape('shape:portal-geo')?.props.color === 'blue')
	await viewer.reload(); await viewer.waitForFunction(() => window.__xpCanvasEditor?.getShape('shape:portal-geo')?.props.color === 'blue')
	assert.equal((await teacher.request.put(`/api/portal/boards/${board.id}/access`, { data: { grants: [] } })).status(), 200)
	await viewer.waitForFunction(() => window.__portalClosed.includes(4099))
	assert.equal((await student.request.get(`/api/boards/${board.id}`)).status(), 404)
	assert.equal((await student.request.get(`/api/uploads/${uploadId}`, { headers: { 'if-none-match': visibleAsset.headers().etag } })).status(), 404)
	assert.equal((await teacher.request.put(`/api/portal/boards/${board.id}/access`, { data: { grants: [{ kind: 'user', subjectId: ana.id }] } })).status(), 200)
	await viewer.reload(); await viewer.waitForFunction(() => !!window.__xpCanvasEditor?.getShape('shape:portal-geo'))
	assert.equal((await teacher.request.post(`/api/portal/students/${ana.id}/reset`)).status(), 200)
	await viewer.waitForFunction(() => window.__portalClosed.includes(4099))
	assert.equal((await student.request.get('/api/library')).status(), 401)
	assert.equal((await anonymous.request.post('/api/portal/login', { data: { username: anaUsername, password: 'otra frase de prueba segura' } })).status(), 401)
	const resetLogin = await anonymous.request.post('/api/portal/login', { data: { username: anaUsername, password: anaUsername } })
	assert.equal(resetLogin.status(), 200); assert.equal((await resetLogin.json()).user.mustChangePassword, true)
	assert.equal((await teacher.request.patch(`/api/portal/students/${ana.id}`, { data: { disabled: true } })).status(), 200)
	assert.equal((await anonymous.request.post('/api/portal/login', { data: { username: anaUsername, password: anaUsername } })).status(), 401)
	assert.equal((await teacher.request.put(`/api/portal/boards/${privateBoard.id}/access`, { data: { grants: [] }, headers: { origin: 'https://hostile.test' } })).status(), 403)
	for (let index = 0; index < 13; index++) {
		const response = await anonymous.request.post('/api/portal/login', { data: { username: `X${stamp}`, password: 'wrong-password' } })
		assert.equal(response.status(), index < 12 ? 401 : 429)
	}
	const exported = await (await teacher.request.get(`/api/boards/${board.id}/export`)).json()
	const imported = await teacher.request.post('/api/boards/import', { data: { version: 1, name: `Copia QA ${stamp}`, snapshot: exported.snapshot } })
	assert.equal(imported.status(), 201)
	const copy = await imported.json()
	assert.notEqual(copy.id, board.id)
	const copyExport = await (await teacher.request.get(`/api/boards/${copy.id}/export`)).json()
	const records = (snapshot) => snapshot.documents.map((d) => d.state).sort((a, b) => a.id.localeCompare(b.id))
	assert.deepEqual(records(copyExport.snapshot), records(exported.snapshot))
	assert.deepEqual((await (await teacher.request.get(`/api/portal/boards/${copy.id}/access`)).json()).grants, [])
	assert.equal((await teacher.request.post('/api/boards/import', { data: { version: 1, name: 'Bad snapshot', snapshot: {} } })).status(), 400)
	assert.equal((await teacher.request.post('/api/portal/logout')).status(), 200)
	assert.equal((await teacher.request.get('/api/library')).status(), 401)
	assert.deepEqual(errors, [])
	console.log('Portal smoke passed: initial password, welcome gate, profile, pass download/customizer, password change, teacher-only document transfer, roster/groups, private library and assets, read-only sync, bound presence, revocation, reset, CSRF and rate limits.')
} finally { await browser.close() }
